# This is a basic workflow to help you get started with Actions

name: Java CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test

      - name: run build
        run: ./gradlew clean build -x test

  CD:
    runs-on: ubuntu-latest
    needs: CI
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test

      - name: run build
        run: ./gradlew clean build -x test

      - name: Build Docker Image
        run: sudo docker build --tag infowargame .

      - name: Upload to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: seogunhee4/backend_infowargame_v3
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
